import {
  JoseKey,
  Keyset,
  NodeOAuthClient,
  buildAtprotoLoopbackClientMetadata,
} from "@atproto/oauth-client-node";
import type {
  NodeSavedSession,
  NodeSavedState,
  OAuthClientMetadataInput,
} from "@atproto/oauth-client-node";
import { getDb } from "../db";
import { getUnpatchedFetch } from "./unpatched-fetch";

export const SCOPE = "atproto transition:generic";

let client: NodeOAuthClient | null = null;

const PUBLIC_URL = process.env.PUBLIC_URL;
const PRIVATE_KEY = process.env.PRIVATE_KEY;

/**
 * Optional dev-only escape hatch for pointing the OAuth client at a local
 * in-process PDS + PLC spun up by `scripts/dev-network.ts`. BOTH must be
 * set for the gate to engage; if either is unset, production/loopback
 * behavior is completely unchanged. No localhost fallback.
 *
 * SECURITY: do not read these in production. They are only consulted at
 * client construction. Unset in real deploys and the `NodeOAuthClient`
 * defaults (real `plc.directory`, real DNS handle resolution) apply.
 */
const DEV_HANDLE_RESOLVER = process.env.SMELLGATE_DEV_HANDLE_RESOLVER;
const DEV_PLC_URL = process.env.SMELLGATE_DEV_PLC_URL;
const DEV_NETWORK_ENABLED = Boolean(DEV_HANDLE_RESOLVER && DEV_PLC_URL);

function getClientMetadata(): OAuthClientMetadataInput {
  if (PUBLIC_URL) {
    // Hosted-path metadata. The `client_id` MUST be a URL the auth server
    // can fetch; we serve the same shape from
    // `app/oauth-client-metadata.json/route.ts`. JWKS for the
    // `private_key_jwt` client assertion is served from
    // `app/.well-known/jwks.json/route.ts` (public components only).
    // `token_endpoint_auth_signing_alg` MUST match the key algorithm
    // generated by `scripts/gen-key.ts` (currently ES256 / P-256).
    return {
      client_id: `${PUBLIC_URL}/oauth-client-metadata.json`,
      client_name: "smellgate",
      client_uri: PUBLIC_URL,
      redirect_uris: [`${PUBLIC_URL}/oauth/callback`],
      grant_types: ["authorization_code", "refresh_token"],
      response_types: ["code"],
      scope: SCOPE,
      token_endpoint_auth_method: "private_key_jwt" as const,
      token_endpoint_auth_signing_alg: "ES256" as const,
      jwks_uri: `${PUBLIC_URL}/.well-known/jwks.json`,
      application_type: "web" as const,
      dpop_bound_access_tokens: true,
    };
  } else {
    return buildAtprotoLoopbackClientMetadata({
      scope: SCOPE,
      redirect_uris: ["http://127.0.0.1:3000/oauth/callback"],
    });
  }
}

async function getKeyset(): Promise<Keyset | undefined> {
  if (PUBLIC_URL && PRIVATE_KEY) {
    return new Keyset([await JoseKey.fromJWK(JSON.parse(PRIVATE_KEY))]);
  } else {
    return undefined;
  }
}

export async function getOAuthClient(): Promise<NodeOAuthClient> {
  if (client) return client;

  client = new NodeOAuthClient({
    clientMetadata: getClientMetadata(),
    keyset: await getKeyset(),

    // Production bug (prod trace 2026-04-18T03:15:50Z): every write path
    // (shelf-add, review, description, vote, comment, submission) crashes
    // with `TypeError: fetch failed` / `expected non-null body source`
    // on Fly's Node 24 alpine runtime. Root cause is an interaction
    // between Next.js 16's `patch-fetch` wrapper, `@atproto/oauth-client`'s
    // DPoP `new Request(input, init)` call, and the undici 7 bundled with
    // Node 24.15+ (24.11 does not trigger it, which is why integration
    // tests on the Codespace pass).
    //
    // The sequence:
    //   1. dpopFetchWrapper builds `new Request(url, { body: string, ... })`
    //      — undici sets `body.source` to the string, so the body is
    //      re-extractable.
    //   2. It then calls `fetch(request)`. In Next's route-handler
    //      runtime, this `fetch` is the patched one.
    //   3. Next's patched fetch (see `doOriginalFetch` in
    //      `next/dist/server/lib/patch-fetch.js`) sees the Request and
    //      rebuilds it: `new Request(request.url, { body: request.body })`
    //      — now `body` is a ReadableStream and `body.source` is null.
    //   4. The PDS responds 401 (DPoP nonce challenge). undici 7's fetch
    //      spec-compliant retry path then runs `safelyExtractBody(
    //      request.body.source)` on the credentialed retry — and throws
    //      `expected non-null body source` because `source` is null.
    //
    // Fix: give the OAuth client a fetch that bypasses Next's patch, so
    // the dpop-wrapped Request is the only Request (single wrap →
    // `body.source` preserved → undici's 401 retry can re-extract it).
    // The PDS traffic is server-to-server and never benefits from Next's
    // fetch cache anyway (POST, Authorization header), so bypassing the
    // wrap costs nothing. See `lib/auth/unpatched-fetch.ts` for details.
    fetch: getUnpatchedFetch(),

    // Dev-network gate: when both env vars are set (by `pnpm dev:network`),
    // resolve handles + DIDs against the local in-process PDS/PLC instead
    // of the public ones. Both unset = production defaults, untouched.
    ...(DEV_NETWORK_ENABLED
      ? {
          allowHttp: true,
          handleResolver: DEV_HANDLE_RESOLVER!,
          plcDirectoryUrl: DEV_PLC_URL!,
        }
      : {}),

    stateStore: {
      async get(key: string) {
        const db = getDb();
        const row = await db
          .selectFrom("auth_state")
          .select("value")
          .where("key", "=", key)
          .executeTakeFirst();
        return row ? JSON.parse(row.value) : undefined;
      },
      async set(key: string, value: NodeSavedState) {
        const db = getDb();
        const valueJson = JSON.stringify(value);
        await db
          .insertInto("auth_state")
          .values({ key, value: valueJson })
          .onConflict((oc) =>
            oc.column("key").doUpdateSet({ value: valueJson }),
          )
          .execute();
      },
      async del(key: string) {
        const db = getDb();
        await db.deleteFrom("auth_state").where("key", "=", key).execute();
      },
    },

    sessionStore: {
      async get(key: string) {
        const db = getDb();
        const row = await db
          .selectFrom("auth_session")
          .select("value")
          .where("key", "=", key)
          .executeTakeFirst();
        return row ? JSON.parse(row.value) : undefined;
      },
      async set(key: string, value: NodeSavedSession) {
        const db = getDb();
        const valueJson = JSON.stringify(value);
        await db
          .insertInto("auth_session")
          .values({ key, value: valueJson })
          .onConflict((oc) =>
            oc.column("key").doUpdateSet({ value: valueJson }),
          )
          .execute();
      },
      async del(key: string) {
        const db = getDb();
        await db.deleteFrom("auth_session").where("key", "=", key).execute();
      },
    },
  });

  return client;
}
